// Generated by CoffeeScript 1.6.2
(function() {
  var active, chrome, requestMethods;

  chrome = this.chrome;

  active = true;

  chrome.browserAction.onClicked.addListener(function(tab) {
    if (active === false) {
      active = true;
      return chrome.browserAction.setIcon({
        path: 'icons/ghost64.png'
      });
    } else {
      active = false;
      return chrome.browserAction.setIcon({
        path: 'icons/ghost_gray64.png'
      });
    }
  });

  requestMethods = {
    'getActive': function() {
      return active;
    }
  };

  chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
    if (typeof requestMethods[request.method] === 'function') {
      return sendResponse({
        data: requestMethods[request.method]()
      });
    } else {
      return sendResponse({
        data: {}
      });
    }
  });

}).call(this);
